### ISSUE TITLE
HD44780_CursorOn(); 

### ISSUE THREAD

**Issue by adekpp** [Matiasus/HD44780#13]
Hi,
Your library is great! but I'm having a little trouble. After compilation with `HD44780_CursorOn();` everything is ok but if I want to disable cursor and compile without `HD44780_CursorOn();` the lcd display is blank.

**Comment by Matiasus** [comment]
Hi,

many thanks. Functions [HD44780_CursorOn()](https://github.com/Matiasus/HD44780#hd44780_cursoron), [HD44780_CursorBlink()](https://github.com/Matiasus/HD44780#hd44780_cursorblink) besides the cursor on or blink, switch the display on, so you don't need to use function [HD44780_DisplayOn()](https://github.com/Matiasus/HD44780#hd44780_displayon). But without functions [HD44780_CursorOn()](https://github.com/Matiasus/HD44780#hd44780_cursoron), [HD44780_CursorBlink()](https://github.com/Matiasus/HD44780#hd44780_cursorblink) display is switched on by the function [HD44780_DisplayOn()](https://github.com/Matiasus/HD44780#hd44780_displayon).

Marián
