### ISSUE TITLE
Can't compile it

### ISSUE THREAD

**Issue by ArbenP** [Matiasus/HD44780#14]
Hi, getting this error when trying to compile it:
`root@DietPi:/home/dietpi/HD44780# gcc main.c
main.c:17:10: fatal error: util/delay.h: No such file or directory
   17 | #include <util/delay.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.`

**Comment by Matiasus** [comment]
1. You should install avr-libc package that <util/delay.h> is a part of. 
2. You should compile program with avr-gcc, not with gcc. See the [Makefile](https://github.com/Matiasus/HD44780/blob/master/Makefile).

**Comment by ArbenP** [comment]
Thanks worked
